### ISSUE TITLE
NPE in SimpleSpanProcessor

### ISSUE THREAD

**Issue by skundrik** [jenkinsci/opentelemetry-plugin#105]
### Version report

Jenkins versions report:

```
Jenkins: 2.263.4
OS: Linux - 2.6.32-754.36.1.el6.x86_64
---
opentelemetry:0.10-beta
```

### Reproduction steps

- Installed opentelemetry plugin 0.9
- Observed the following in the logs

```
2021-05-10 01:48:42.087+0000 [id=1367]  WARNING i.o.s.t.e.SimpleSpanProcessor#onEnd: Exporter threw an Exception
java.lang.NullPointerException
        at io.opentelemetry.proto.common.v1.AnyValue$Builder.setStringValue(AnyValue.java:899)
        at io.opentelemetry.exporter.otlp.internal.CommonAdapter.makeStringArrayAnyValue(CommonAdapter.java:132)
        at io.opentelemetry.exporter.otlp.internal.CommonAdapter.makeStringArrayKeyValue(CommonAdapter.java:72)
        at io.opentelemetry.exporter.otlp.internal.CommonAdapter.toProtoAttribute(CommonAdapter.java:36)
        at io.opentelemetry.exporter.otlp.internal.SpanAdapter.lambda$toProtoSpan$0(SpanAdapter.java:102)
        at io.opentelemetry.sdk.trace.AttributesMap.forEach(AttributesMap.java:56)
        at io.opentelemetry.exporter.otlp.internal.SpanAdapter.toProtoSpan(SpanAdapter.java:102)
        at io.opentelemetry.exporter.otlp.internal.SpanAdapter.groupByResourceAndLibrary(SpanAdapter.java:82)
        at io.opentelemetry.exporter.otlp.internal.SpanAdapter.toProtoResourceSpans(SpanAdapter.java:42)
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter.export(OtlpGrpcSpanExporter.java:88)
        at io.opentelemetry.sdk.trace.export.SimpleSpanProcessor.onEnd(SimpleSpanProcessor.java:75)
        at io.opentelemetry.sdk.trace.RecordEventsReadableSpan.endInternal(RecordEventsReadableSpan.java:442)
        at io.opentelemetry.sdk.trace.RecordEventsReadableSpan.end(RecordEventsReadableSpan.java:422)
        at io.jenkins.plugins.opentelemetry.job.MonitoringRunListener._onFinalized(MonitoringRunListener.java:222)
        at io.jenkins.plugins.opentelemetry.job.opentelemetry.OtelContextAwareAbstractRunListener.onFinalized(OtelContextAwareAbstra
ctRunListener.java:59)
        at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:255)
        at hudson.model.Run.onEndBuilding(Run.java:2069)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:636)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:353)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)
```
### Comments
Seems to me that the problem is caused by adding `null` value for sensitive parameters in here https://github.com/jenkinsci/opentelemetry-plugin/blob/9d1e17606121ce3f5269afc1340607fca0446883/src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringRunListener.java#L113-L121
which then leads to https://github.com/open-telemetry/opentelemetry-java/blob/e60857d369a1f10664833483cbb841abd5ee53c3/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/CommonAdapter.java#L129-L135
trying to add `null` value to the list of string parameters that is not supported by the protocol
https://github.com/open-telemetry/opentelemetry-proto/blob/de4fc37940d39370194fb774e634ca408dacd865/opentelemetry/proto/common/v1/common.proto#L24-L39

**Comment by cyrille-leclerc** [comment]
@skundrik can you please test https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-0.11-beta

**Comment by cyrille-leclerc** [comment]
Thanks for the feedback, we will test with Elastic. 
Can you please indicate if you integrate OpenTelemetry with Elastic using the historical OpenTelemetry Collector Exporter for Elastic or if you use the new OpenTelemetry Protocol intake on Elastic APM Server?

**Comment by skundrik** [comment]
The latter, OpenTelemetry directly via APM Server.

**Comment by cyrille-leclerc** [comment]
Thanks Slavo, I have identified the problem and created 
 * Jenkins OpenTelemetry plugin bug [Pipeline parameters are not reported as span attributes by Elastic APM #109](https://github.com/jenkinsci/opentelemetry-plugin/issues/109)
 * Elastic APLM Server bug [[OTLP] Multivalued span attributes are ignored #5250](https://github.com/elastic/apm-server/issues/5250)
