### ISSUE TITLE
Intermittent java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by traviswalker26** [jenkinsci/opentelemetry-plugin#129]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.263.1
OS: Windows Server 2016 - 10.0
---
opentelemetry:0.13
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
- Windows Server 2016 - 10.0
- Linux - 4.14.200-155.322.amzn2.x86_64
```

### Results

Actual result:

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.AbstractMap.toString(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap.toString(AbstractMapBasedMultimap.java:1323)
	at com.google.common.collect.AbstractMultimap.toString(AbstractMultimap.java:253)
	at com.google.common.collect.ArrayListMultimap.toString(ArrayListMultimap.java:65)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService$RunSpans.toString(OtelTraceService.java:244)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$getSpan$1(OtelTraceService.java:81)
	at java.util.logging.Logger.log(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.getSpan(OtelTraceService.java:81)
	at io.jenkins.plugins.opentelemetry.job.OtelEnvironmentContributor.buildEnvironmentFor(OtelEnvironmentContributor.java:26)
	at hudson.model.Run.getEnvironment(Run.java:2442)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:492)
	at hudson.plugins.git.GitSCM.getParamExpandedRepos(GitSCM.java:504)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1205)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1301)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by cyrille-leclerc** [comment]
Can you please test with https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-0.15 and share feedback, the problem should be fixed.

**Comment by traviswalker26** [comment]
Thank you so much for the quick fix. I will let you know if it comes up again.
