### ISSUE TITLE
NullPointerException in CloudBees Disk Usage Plugin

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#201]
### Version report

Jenkins and plugins versions report: 2.303.2 (LTS)

```
2021-11-02 12:08:45.087+0000 [id=117]	SEVERE	h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (Simple disk usage computation [#4]/117) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
	at hudson.Plugin.getConfigXml(Plugin.java:297)
	at hudson.Plugin.save(Plugin.java:281)
	at com.cloudbees.simplediskusage.QuickDiskUsagePlugin$2.run(QuickDiskUsagePlugin.java:267)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

- MacOS

### Reproduction steps

Could it be caused by https://github.com/jenkinsci/opentelemetry-plugin/commit/a933e05145b4b6889c4f1c6e9d9695a4ad187a08 that is part of https://github.com/jenkinsci/opentelemetry-plugin/pull/185 ?

### Results

Expected result:

Actual result:

**Comment by cyrille-leclerc** [comment]
Fixed in v0.22-beta-2
