### ISSUE TITLE
ClassNotFoundException during instantiation of `io.jenkins.plugins.opentelemetry.computer.DiskUsageMonitoringInitializer`

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#202]
### Version report

Jenkins and plugins versions report:

 * Jenkins 2.317
 * opentelemetry-plugin 0.22-beta-1

### Reproduction steps

* Start Jenkins with opentelemetry-plugin 0.22-beta-1 but without CloudBees Simple Disk Usage plugin.

```
2021-11-02 15:54:34.907+0000 [id=283]	WARNING	o.j.h.a.Index$2$1#fetch: Failed to load io.jenkins.plugins.opentelemetry.computer.DiskUsageMonitoringInitializer
java.lang.ClassNotFoundException: com.cloudbees.simplediskusage.QuickDiskUsagePlugin
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1418)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1373)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1128)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: com/cloudbees/simplediskusage/QuickDiskUsagePlugin
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at org.jvnet.hudson.annotation_indexer.Index$2$1.fetch(Index.java:127)
	at org.jvnet.hudson.annotation_indexer.Index$2$1.hasNext(Index.java:92)
	at org.jvnet.hudson.annotation_indexer.SubtypeIterator.fetch(SubtypeIterator.java:18)
	at org.jvnet.hudson.annotation_indexer.SubtypeIterator.hasNext(SubtypeIterator.java:28)
	at hudson.init.TaskMethodFinder.discoverTasks(TaskMethodFinder.java:56)
	at hudson.init.InitializerFinder.discoverTasks(InitializerFinder.java:33)
	at hudson.PluginManager.start(PluginManager.java:981)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:923)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2179)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1846)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by cyrille-leclerc** [comment]
Won't fix, only happens when installing the Otel Jenkins Plugin during the Jenkins first run when choosing to install the default plugins.
