### ISSUE TITLE
Jenkins Otel Plugin fails to start `IncompatibleClassChangeError: Method 'io.opentelemetry.sdk.metrics.SdkMeterProviderBuilder...' must be InterfaceMethodref constant`

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#230]
### Version report

Jenkins 2.303.3
OpenTelemetry Plugin 1.0.0

### Startup logs

```
2021-11-29 14:04:31.361+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @528ms to org.eclipse.jetty.util.log.JavaUtilLog
2021-11-29 14:04:31.432+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2021-11-29 14:04:31.460+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2021-11-29 14:04:31.527+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 11.0.11+9
2021-11-29 14:04:31.900+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2021-11-29 14:04:31.950+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2021-11-29 14:04:31.950+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2021-11-29 14:04:31.951+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2021-11-29 14:04:32.538+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /Users/cyrilleleclerc/.jenkins found at: $user.home/.jenkins
2021-11-29 14:04:33.856+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@6c2f1700{Jenkins v2.303.3,/,file:///Users/cyrilleleclerc/.jenkins/war/,AVAILABLE}{/Users/cyrilleleclerc/.jenkins/war}
2021-11-29 14:04:33.913+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@5e5d171f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-11-29 14:04:33.913+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @3082ms
2021-11-29 14:04:33.914+0000 [id=26]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2021-11-29 14:04:34.180+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2021-11-29 14:04:34.666+0000 [id=41]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/cyrilleleclerc/.jenkins/war/WEB-INF/lib/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-11-29 14:04:41.414+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2021-11-29 14:04:42.365+0000 [id=38]	WARNING	h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration, annotation=[none]]; skipping this component
java.lang.IncompatibleClassChangeError: Method 'io.opentelemetry.sdk.metrics.SdkMeterProviderBuilder io.opentelemetry.sdk.metrics.SdkMeterProvider.builder()' must be InterfaceMethodref constant
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:120)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.newOpenTelemetrySdk(OpenTelemetrySdkAutoConfiguration.java:101)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:177)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:83)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initialize(OpenTelemetrySdkProvider.java:126)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry(JenkinsOpenTelemetryPluginConfiguration.java:121)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:592)
Caused: java.lang.RuntimeException: @PostConstruct public void io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry()
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:594)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error notifying ProvisionListener hudson.ExtensionFinder$GuiceFinder$SezpozModule of io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.
 Reason: java.lang.RuntimeException: @PostConstruct public void io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry()

1 error
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:441)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:401)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:392)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:349)
	at hudson.ExtensionList.load(ExtensionList.java:382)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:318)
	at hudson.ExtensionList.iterator(ExtensionList.java:170)
	at jenkins.model.Jenkins.getDescriptorByType(Jenkins.java:1637)
	at com.cloudbees.jenkins.support.impl.AbstractItemDirectoryComponent.getDescriptor(AbstractItemDirectoryComponent.java:96)
	at com.cloudbees.jenkins.support.impl.AbstractItemDirectoryComponent.getDescriptor(AbstractItemDirectoryComponent.java:30)
	at com.cloudbees.jenkins.support.impl.DirectoryComponent.<init>(DirectoryComponent.java:42)
	at com.cloudbees.jenkins.support.impl.AbstractItemDirectoryComponent.<init>(AbstractItemDirectoryComponent.java:34)
	at com.cloudbees.jenkins.support.impl.AbstractItemDirectoryComponent$$FastClassByGuice$$57694467.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:568)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:441)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:401)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:392)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:349)
	at hudson.ExtensionList.load(ExtensionList.java:382)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:318)
	at hudson.ExtensionList.iterator(ExtensionList.java:170)
	at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821)
	at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.cloudbees.jenkins.support.SupportPlugin.getComponents(SupportPlugin.java:287)
	at com.cloudbees.jenkins.support.SupportPlugin.postInitialize(SupportPlugin.java:650)
	at hudson.PluginManager$2$1$2.run(PluginManager.java:563)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1158)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-11-29 14:04:42.622+0000 [id=36]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2021-11-29 14:04:42.639+0000 [id=34]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2021-11-29 14:04:43.379+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2021-11-29 14:04:43.399+0000 [id=35]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
2021-11-29 14:04:43.728+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2021-11-29 14:04:43.729+0000 [id=42]	INFO	i.j.p.o.i.JvmMonitoringInitializer#initialize: Start monitoring the JVM...
2021-11-29 14:04:43.729+0000 [id=38]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2021-11-29 14:04:43.730+0000 [id=62]	INFO	c.c.s.QuickDiskUsagePlugin$3#run: Waiting for Jenkins to be up before computing disk usage
2021-11-29 14:04:43.734+0000 [id=65]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Download metadata
2021-11-29 14:04:43.736+0000 [id=31]	WARNING	h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration, annotation=[none]]; skipping this component
java.lang.IncompatibleClassChangeError: Method 'io.opentelemetry.sdk.metrics.SdkMeterProviderBuilder io.opentelemetry.sdk.metrics.SdkMeterProvider.builder()' must be InterfaceMethodref constant
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:120)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.newOpenTelemetrySdk(OpenTelemetrySdkAutoConfiguration.java:101)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:177)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:83)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initialize(OpenTelemetrySdkProvider.java:126)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry(JenkinsOpenTelemetryPluginConfiguration.java:121)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:592)
Caused: java.lang.RuntimeException: @PostConstruct public void io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry()
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:594)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error notifying ProvisionListener hudson.ExtensionFinder$GuiceFinder$SezpozModule of io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.
 Reason: java.lang.RuntimeException: @PostConstruct public void io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry()

1 error
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:441)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:401)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:392)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:349)
	at hudson.ExtensionList.load(ExtensionList.java:382)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:318)
	at hudson.ExtensionList.iterator(ExtensionList.java:170)
	at hudson.ExtensionList.get(ExtensionList.java:147)
	at org.jenkinsci.main.modules.sshd.SSHD.get(SSHD.java:263)
	at org.jenkinsci.main.modules.sshd.SSHD.init(SSHD.java:268)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:180)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1158)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-11-29 14:04:43.744+0000 [id=65]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Download metadata. 9 ms
2021-11-29 14:04:43.864+0000 [id=34]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2021-11-29 14:04:43.910+0000 [id=25]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
```

**Comment by cyrille-leclerc** [comment]
The release is broken, the opentelemetry +1.0.0 HPI contains both otel 1.7.1 and 1.9.0 jars

```
annotations-4.1.1.4.jar
error_prone_annotations-2.10.0.jar
grpc-api-1.41.0.jar
grpc-api-1.42.1.jar
grpc-context-1.41.0.jar
grpc-context-1.42.1.jar
grpc-core-1.42.1.jar
grpc-netty-shaded-1.42.1.jar
grpc-stub-1.42.1.jar
gson-2.8.6.jar
guava-20.0.jar
jackson-core-2.13.0.jar
jackson-databind-2.13.0.jar
jackson-jr-objects-2.13.0.jar
okhttp-3.14.9.jar
okio-1.17.2.jar
opentelemetry-api-1.7.1.jar
opentelemetry-api-1.9.0.jar
opentelemetry-api-metrics-1.7.1-alpha.jar
opentelemetry-api-metrics-1.9.0-alpha.jar
opentelemetry-context-1.7.1.jar
opentelemetry-context-1.9.0.jar
opentelemetry-exporter-jaeger-1.7.1.jar
opentelemetry-exporter-jaeger-1.9.0.jar
opentelemetry-exporter-logging-1.7.1.jar
opentelemetry-exporter-logging-1.9.0.jar
opentelemetry-exporter-otlp-1.7.1.jar
opentelemetry-exporter-otlp-1.9.0.jar
opentelemetry-exporter-otlp-common-1.7.1.jar
opentelemetry-exporter-otlp-common-1.9.0.jar
opentelemetry-exporter-otlp-metrics-1.7.1-alpha.jar
opentelemetry-exporter-otlp-metrics-1.9.0-alpha.jar
opentelemetry-exporter-otlp-trace-1.7.1.jar
opentelemetry-exporter-otlp-trace-1.9.0.jar
opentelemetry-exporter-prometheus-1.7.1-alpha.jar
opentelemetry-exporter-prometheus-1.9.0-alpha.jar
opentelemetry-sdk-1.7.1.jar
opentelemetry-sdk-1.9.0.jar
opentelemetry-sdk-common-1.7.1.jar
opentelemetry-sdk-common-1.9.0.jar
opentelemetry-sdk-extension-autoconfigure-1.7.1-alpha.jar
opentelemetry-sdk-extension-autoconfigure-1.9.0-alpha.jar
opentelemetry-sdk-extension-autoconfigure-spi-1.7.1.jar
opentelemetry-sdk-extension-autoconfigure-spi-1.9.0.jar
opentelemetry-sdk-extension-resources-1.7.1.jar
opentelemetry-sdk-extension-resources-1.9.0.jar
opentelemetry-sdk-logs-1.9.0-alpha.jar
opentelemetry-sdk-metrics-1.7.1-alpha.jar
opentelemetry-sdk-metrics-1.9.0-alpha.jar
opentelemetry-sdk-trace-1.7.1.jar
opentelemetry-sdk-trace-1.9.0.jar
opentelemetry-semconv-1.7.1-alpha.jar
opentelemetry-semconv-1.9.0-alpha.jar
opentelemetry.jar
perfmark-api-0.23.0.jar
simpleclient_common-0.12.0.jar
simpleclient_httpserver-0.12.0.jar
simpleclient_tracer_common-0.12.0.jar
simpleclient_tracer_otel_agent-0.12.0.jar
simpleclient_tracer_otel-0.12.0.jar
simpleclient-0.12.0.jar
```

**Comment by cyrille-leclerc** [comment]
Fixed by https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-1.0.1
