### ISSUE TITLE
Failure on delete: VerifyException

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#342]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

2.0.0

### Reproduction steps

@kuisathaverat to describe

### Expected Results

No exception

### Actual Results

```
[jenkins.log][WARNING] RunListener failed
com.google.common.base.VerifyException: jenkins-heartbeat-monitor #21954 - Can't access run phase span while there are remaining pipeline step spans: RunSpans{runPhasesSpans=[
RecordEventsReadableSpan{
     traceId=d88f1429b221524a472a88ff41ef16b2,
     spanId=9b2660a2fc6f1829,
     parentSpanContext=ImmutableSpanContext{
         traceId=00000000000000000000000000000000,
         spanId=0000000000000000,
         traceFlags=00,
         traceState=ArrayBasedTraceState{entries=[]},
         remote=false,
         valid=false},
     name=jenkins-heartbeat-monitor,
     kind=SERVER,
     attributes=AttributesMap{
         data={
             ci.pipeline.type=workflow,
             ci.pipeline.run.url=https://apm-ci.elastic.co/job/jenkins-heartbeat-monitor/21954/,
             ci.pipeline.id=jenkins-heartbeat-monitor,
             type=job,
             ci.pipeline.run.cause=[UserIdCause:local-admin],
             ci.pipeline.run.committers=[],
             ci.pipeline.run.number=21954,
             ci.pipeline.name=jenkins-heartbeat-monitor},
         capacity=128,
         totalAddedValues=8},
     status=ImmutableStatusData{
         statusCode=UNSET,
         description=},
     totalRecordedEvents=0,
     totalRecordedLinks=0,
     startEpochNanos=1645687222608000000,
     endEpochNanos=0},
 RecordEventsReadableSpan{
     traceId=d88f1429b221524a472a88ff41ef16b2,
     spanId=7a5a2ee9f1138cbf,
     parentSpanContext=ImmutableSpanContext{
         traceId=d88f1429b221524a472a88ff41ef16b2,
         spanId=9b2660a2fc6f1829,
         traceFlags=01,
         traceState=ArrayBasedTraceState{entries=[]},
         remote=false,
         valid=true},
     name=Phase: Run,
     kind=INTERNAL,
     attributes=null,
     status=ImmutableStatusData{statusCode=UNSET,
     description=},
     totalRecordedEvents=0,
     totalRecordedLinks=0,
     startEpochNanos=1645687222608689256,
     endEpochNanos=0}],
 pipelineStepSpansByFlowNodeId={
    13=
    [PipelineSpanContext{
        span=RecordEventsReadableSpan{
            traceId=d88f1429b221524a472a88ff41ef16b2,
             spanId=fb04f6fc430faf49,
             parentSpanContext=ImmutableSpanContext{
                traceId=d88f1429b221524a472a88ff41ef16b2,
                 spanId=a61217cdb80379d7,
                 traceFlags=01,
                 traceState=ArrayBasedTraceState{entries=[]},
                 remote=false,
                 valid=true},
             name=Agent,
             kind=INTERNAL,
             attributes=AttributesMap{data={jenkins.pipeline.step.name=agent,
             jenkins.pipeline.step.type=node,
             jenkins.pipeline.step.id=13,
             jenkins.pipeline.step.plugin.name=workflow-durable-task-step,
             jenkins.pipeline.step.agent.label=jenkins-heartbeat,
             jenkins.pipeline.step.plugin.version=1121.va_65b_d2701486},
             capacity=128,
             totalAddedValues=6},
             status=ImmutableStatusData{statusCode=UNSET,
             description=},
             totalRecordedEvents=0,
             totalRecordedLinks=0,
             startEpochNanos=1645687227879404958,
             endEpochNanos=0}
        flowNodeId=13,
        parentIds=[13, 12]}
        ]}}
	at com.google.common.base.Verify.verify(Verify.java:122)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.getSpan(OtelTraceService.java:84)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.getSpan(OtelTraceService.java:75)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.setupContext(OtelTraceService.java:315)
	at io.jenkins.plugins.opentelemetry.job.opentelemetry.OtelContextAwareAbstractRunListener.onDeleted(OtelContextAwareAbstractRunListener.java:101)
```

**Comment by cyrille-leclerc** [comment]
When `OtelTraceService.setupContext()` is invoked by `OtelContextAwareAbstractRunListener.onDeleted()` should `OtelTraceService#getSpan(Run, verify=false)` rather than `OtelTraceService#getSpan(Run, verify=true)`
