### ISSUE TITLE
Option to skip certificate checks

### ISSUE THREAD

**Issue by timmjd** [jenkinsci/opentelemetry-plugin#480]
### What feature do you want to see added?

Can you please add an option to bypass the SSL certificate check for the log storage / communication?

![image](https://user-images.githubusercontent.com/508684/178271398-a9b8717e-2aca-4566-b739-cf323e77e107.png)

# Reason

If you deploy Elasticsearch via [Elastic Cloud on Kubernetes (ECK)](https://github.com/elastic/cloud-on-k8s), security and SSL communication is enabled by default. But due to the operator usually will take care about the certificate creation and setup, the generated certificates will be self signed.

The __workaround__ for this missing feature would be:
* Go via a public signed Ingress of the cluster if it's signed by a public trusted certificate
* Deploy the elastic certificate to all Jenkins instances
* Inject a custom certificate into elastic operator

Therefore, having a simple button to work with SSL - but ignore SSL certificates would be awesome due to the deployment would become way more simpler.

# Error log

```
2022-07-11 13:04:57.242+0000 [id=15]    WARNING    h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: it.writeLogTo(offset,output) in /job/test/33/console. Reason: java.lang.RuntimeException: javax.net.ssl.SSLHandsun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
    at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
Caused: sun.security.validator.ValidatorException: PKIX path building failed
    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
    at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
    at java.base/sun.security.validator.Validator.validate(Validator.java:264)
    at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
    at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
    Caused: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)                                                                                                                
```

**Comment by cyrille-leclerc** [comment]
That's a great suggestion, thanks for the feedback.

**Comment by cyrille-leclerc** [comment]
@timmjd could you by any chance test the PR 
* https://github.com/jenkinsci/opentelemetry-plugin/pull/481

**Comment by cyrille-leclerc** [comment]
Thanks @timmjd , I'm cutting a version 2.9.0-rc1 with just this change so you are unblocked.

**Comment by apollo909** [comment]
@cyrille-leclerc   how to configure mTLS between plugin and collector,  is it by setting otel properties like,

otel.exporter.otlp.client.key=/var/tmp/key.pem
otel.exporter.otlp.client.certificate=/var/tmp/cert.pem

thank you :)
