### ISSUE TITLE
IncompatibleClassChangeError with OT `current` method.

### ISSUE THREAD

**Issue by Omeramsc** [jenkinsci/opentelemetry-plugin#501]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>
  ```
Jenkins: 2.319.3
OS: Linux - 4.18.0-372.19.1.el8_6.x86_64
---
ace-editor:1.1
ant:1.11
antisamy-markup-formatter:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
blueocean:1.24.8
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.24.8
blueocean-commons:1.24.8
blueocean-config:1.24.8
blueocean-core-js:1.24.8
blueocean-dashboard:1.24.8
blueocean-display-url:2.4.1
blueocean-events:1.24.8
blueocean-git-pipeline:1.24.8
blueocean-github-pipeline:1.24.8
blueocean-i18n:1.24.8
blueocean-jwt:1.24.8
blueocean-personalization:1.24.8
blueocean-pipeline-api-impl:1.24.8
blueocean-pipeline-editor:1.24.8
blueocean-pipeline-scm-api:1.24.8
blueocean-rest:1.24.8
blueocean-rest-impl:1.24.8
blueocean-web:1.24.8
bootstrap4-api:4.6.0-3
bouncycastle-api:2.25
branch-api:2.1044.v2c007e51b_87f
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:746.v350d2781c184
cloudbees-folder:6.714.v79e858ef76a_2
command-launcher:1.2
conditional-buildstep:1.4.1
config-file-provider:3.8.1
configuration-as-code:1.55.1
configuration-as-code-groovy:1.1
credentials:2.6.1.1
credentials-binding:1.27.1
display-url-api:2.3.5
docker-commons:1.18
durable-task:493.v195aefbb0ff2
echarts-api:5.0.2-1
favorite:2.4.1
font-awesome-api:5.15.2-2
git:4.11.3
git-client:3.11.0
git-server:1.10
github:1.34.3
github-api:1.122
github-branch-source:2.10.2
google-oauth-plugin:1.0.6
groovy:442.v817e6d937d6c
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.25
jackson2-api:2.13.3-285.vc03c0256d517
javadoc:1.0
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-2
jaxb:2.3.6-1
jdk-tool:1.0
jenkins-design-language:1.24.8
jira:3.7.1
jjwt-api:0.11.2-5.143e44951c52
job-dsl:1.78.3
jquery3-api:3.6.0-1
jsch:0.1.55.2
junit:1.53
kubernetes:1.31.0
kubernetes-client-api:5.10.1-171.vaa0774fb8c20
kubernetes-credentials:0.9.0
lockable-resources:2.11
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
matrix-auth:2.6.8
matrix-project:771.v574584b_39e60
maven-plugin:3.7
mercurial:2.15
metrics:4.0.2.8.1
oauth-credentials:0.4
okhttp-api:4.9.3-105.vb96869f8ac3a
openshift-client:1.0.37
openshift-login:1.0.27
openshift-sync:1.0.53
opentelemetry:2.9.0
pam-auth:1.6
parameterized-trigger:2.43.1
pipeline-build-step:2.18
pipeline-graph-analysis:1.10
pipeline-input-step:2.12
pipeline-milestone-step:1.3.1
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.15
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:1.9.3
pipeline-utility-steps:2.12.0
plain-credentials:1.8
plugin-util-api:2.4.0
popper-api:1.16.1-2
prometheus:2.0.10
pubsub-light:1.13
run-condition:1.3
scm-api:608.vfa_f971c5a_a_e9
script-security:1138.v8e727069a_025
snakeyaml-api:1.29.1
sse-gateway:1.24
ssh-credentials:1.19
sshd:3.0.4
structs:324.va_f5d6774f3a_d
subversion:2.15.4
token-macro:308.v4f2b_ed62b_b_16
trilead-api:1.0.13
variant:1.4
windows-slaves:1.0
workflow-api:1153.vb_912c0e47fb_a_
workflow-basic-steps:2.24
workflow-cps:2660.2664.v4c114e93f4c1
workflow-cps-global-lib:566.vd0a_a_3334a_555
workflow-durable-task-step:2.40
workflow-job:1145.v7f2433caa07f
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:2.13
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:813.vb_d7c3d2984a_0

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I'm running Jenkins v2.319.3 on a pod deployed with podman v4.1.1 from my RHEL machine. 

### Reproduction steps

1. build and run a jenkins container (I use quay.io/openshift/origin-jenkins:4.12.0)
2. Install and configure the plugin (opentelemetry:2.9.0)
3. create a pipeline script with the following code:

```
import io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider as ots
import io.opentelemetry.api.trace.Span

traceFunc()

@NonCPS
def traceFunc(){

    def tracer = ots.get().getTracer()
    def randomSpan = tracer.spanBuilder("do-something").startSpan()
    )
    println(Span.current())
    randomSpan.end()
}
```
4. run it.

### Expected Results

Info about the current span is printed

### Actual Results

```
java.lang.IncompatibleClassChangeError: Method 'io.opentelemetry.api.trace.Span io.opentelemetry.api.trace.Span.current()' must be InterfaceMethodref constant
	at io.opentelemetry.api.trace.Span$current.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.kohsuke.groovy.sandbox.impl.Checker$2.call(Checker.java:194)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onStaticCall(GroovyInterceptor.java:35)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onStaticCall(SandboxInterceptor.java:187)
	at org.kohsuke.groovy.sandbox.impl.Checker$2.call(Checker.java:192)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedStaticCall(Checker.java:196)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:103)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at WorkflowScript.traceFunc(WorkflowScript:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:12)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:403)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:97)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:315)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:279)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

### Anything else?

What I want to achieve is to output the context of the current span, as well as the span of the pipeline itself, and use it to link\make them parent and child spans \ get the info in a completely different pipeline, and link their spans together.
I don't mind using a different solution.

**Comment by v1v** [comment]
Can you use the context propagation with some environment variables available for each shell/bat step?

https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/job-traces.md


Those env variables are the ones used to integrate Jenkins with some other tools such as maven, ansible, pytest, otel-cli. Those integrations are the ones reading those env variables of they are available. They are not standardized yet, though there is an open issue in the opentelemetry about this, i don't have the link, I'll update this comment later with the reference.

Otherwise, I don't know if you can access the opentelemetry SDK internals.

**Comment by v1v** [comment]
@Omeramsc , I'll close this issue now, the context propagation with the env variables can help to glue the integrations. If you find a different use case please reopen this issue with further details 

Thanks
