### ISSUE TITLE
Configuration exception: `ConfigurationException: Invalid map property: otel.exporter.otlp.headers=api-key=`

### ISSUE THREAD

**Issue by bikrampaul123** [jenkinsci/opentelemetry-plugin#600]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins is not starting after installation of the opentelemetry. 
Jenkins version 2.375.2 (Running as POD)
Opentelemetry Version : 2.11

```
SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: Invalid map property: otel.exporter.otlp.headers=api-key=
        at
````

### Reproduction steps

Jenkins is not starting after installation of the opentelemetry. 
Jenkins version 2.375.2 (Running as POD)
Opentelemetry Version : 2.11

```
SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: Invalid map property: otel.exporter.otlp.headers=api-key=
        at
```

### Expected Results

Jenkins crashed 

### Actual Results

Jenkins should work with OPentelemetry plugin and after installation we should be configure it with manage jenkins.

**Comment by cyrille-leclerc** [comment]
Hello @bikrampaul123 .

The value of the header `api-key` is missing, causing the exception. OTLP header values MUST NOT be empty.

Can you please test with a proper value for the header `api-key`?

![image](https://user-images.githubusercontent.com/459691/224723023-d9779729-4a1c-44fa-a5e9-88274d02f476.png)


<details>
<summary>Detailed stacktrace for `ConfigurationException: Invalid map property: otel.exporter.otlp.headers=api-key=` </summary>

```
2023-03-13 13:51:57.590+0000 [id=21]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID b7c865b9-bb2b-4f9e-b8cc-308891bcb839
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: Invalid map property: otel.exporter.otlp.headers=api-key=
	at io.opentelemetry.sdk.autoconfigure.spi.internal.DefaultConfigProperties.lambda$getMap$6(DefaultConfigProperties.java:217)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.opentelemetry.sdk.autoconfigure.spi.internal.DefaultConfigProperties.getMap(DefaultConfigProperties.java:224)
	at io.opentelemetry.exporter.internal.otlp.OtlpConfigUtil.configureOtlpExporterBuilder(OtlpConfigUtil.java:86)
	at io.opentelemetry.exporter.otlp.internal.OtlpMetricExporterProvider.createExporter(OtlpMetricExporterProvider.java:57)
	at io.opentelemetry.sdk.autoconfigure.SpiUtil.lambda$loadConfigurable$0(SpiUtil.java:48)
	at io.opentelemetry.sdk.autoconfigure.NamedSpiManager.tryLoadImplementationForName(NamedSpiManager.java:46)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.opentelemetry.sdk.autoconfigure.NamedSpiManager.getByName(NamedSpiManager.java:36)
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureExporter(MetricExporterConfiguration.java:77)
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureReader(MetricExporterConfiguration.java:55)
	at io.opentelemetry.sdk.autoconfigure.MeterProviderConfiguration.lambda$configureMetricReaders$0(MeterProviderConfiguration.java:89)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.opentelemetry.sdk.autoconfigure.MeterProviderConfiguration.configureMetricReaders(MeterProviderConfiguration.java:92)
	at io.opentelemetry.sdk.autoconfigure.MeterProviderConfiguration.configureMeterProvider(MeterProviderConfiguration.java:65)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:340)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initializeOtlp(OpenTelemetrySdkProvider.java:144)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initialize(OpenTelemetrySdkProvider.java:118)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry(JenkinsOpenTelemetryPluginConfiguration.java:218)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.configure(JenkinsOpenTelemetryPluginConfiguration.java:164)
	at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:4017)
	at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:3981)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
	at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
	at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
	at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:558)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
```
</details>

**Comment by cyrille-leclerc** [comment]
Please reopen if this doesn't fix the problem
