### ISSUE TITLE
Config `otel.metrics.exporter=none` causes OTel SDK config exception

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#691]
### Jenkins and plugins versions report

Jenkins OTel 2.13.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

MacOS

### Reproduction steps

Configure Jenkins OTel SDK with
* OTLP endpoint like `http://localhost:4317
* Config property `otel.metrics.exporter=none`

### Expected Results

OTel SDK is configured and metrics are NOT exported

### Actual Results

Saving the config failswith

```
Caught unhandled exception with ID ....................................................
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: otel.metrics.exporter contains none along with other exporters
	at io.opentelemetry.sdk.autoconfigure.MeterProviderConfiguration.configureMetricReaders(MeterProviderConfiguration.java:64)
	at io.opentelemetry.sdk.autoconfigure.MeterProviderConfiguration.configureMeterProvider(MeterProviderConfiguration.java:51)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:348)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initializeOtlp(OpenTelemetrySdkProvider.java:160)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initialize(OpenTelemetrySdkProvider.java:131)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry(JenkinsOpenTelemetryPluginConfiguration.java:222)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.configure(JenkinsOpenTelemetryPluginConfiguration.java:165)
	at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:4039)
	at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:4003)
```

**Comment by cyrille-leclerc** [comment]
Fixed in 2.16.0
