### ISSUE TITLE
Override global configuration remains previous broken configuration

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#76]
### Results

When updating the authorisation from `authentication: "noAuthentication"` to `authentication: "otlpHeaderAuthentication"` with a wrong configuration, the configuration cannot be updated afterwards and it remains the previous configuration.

```
java.lang.IllegalArgumentException: Invalid character '=' in key name 'authorization=bearer'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:239)
	at io.grpc.Metadata$Key.validateName(Metadata.java:742)
	at io.grpc.Metadata$Key.<init>(Metadata.java:750)
	at io.grpc.Metadata$Key.<init>(Metadata.java:668)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954)
	at io.grpc.Metadata$Key.of(Metadata.java:705)
	at io.grpc.Metadata$Key.of(Metadata.java:701)
	at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.addHeader(OtlpGrpcSpanExporterBuilder.java:117)
	at io.jenkins.plugins.opentelemetry.authentication.HeaderAuthentication.configure(HeaderAuthentication.java:63)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initializeForGrpc(OpenTelemetrySdkProvider.java:129)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initialize(OpenTelemetrySdkProvider.java:216)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry(JenkinsOpenTelemetryPluginConfiguration.java:88)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.setAuthentication(JenkinsOpenTelemetryPluginConfiguration.java:129)
```

Therefore there is no an easy way to update with a new configuration.

Actual result:

![image](https://user-images.githubusercontent.com/2871786/115150141-03bd3180-a05f-11eb-8d34-847ffa1d83aa.png)

**Comment by v1v** [comment]
I've tried with JCasC to override the manual configuration with the one in source control, but same issue

https://gist.github.com/v1v/b64d827fdb461c3ce942065ec9d27bfd

**Comment by cyrille-leclerc** [comment]
Close, Can't reproduce
