### ISSUE TITLE
[Regresion] testFreestyleJob_with_ant_plugin test is failling

### ISSUE THREAD

**Issue by kuisathaverat** [jenkinsci/opentelemetry-plugin#775]
### Jenkins and plugins versions report

After merging a Jenkin core bump at https://github.com/jenkinsci/opentelemetry-plugin/pull/756 the test `io.jenkins.plugins.opentelemetry.JenkinsOtelPluginFreestyleIntegrationTest.testFreestyleJob_with_ant_plugin` it is failing

```
java.lang.AssertionError: 

Expected: is "jenkins-core"
     but: was "ant"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.jenkins.plugins.opentelemetry.BaseIntegrationTest.assertBuildStepMetadata(BaseIntegrationTest.java:237)
	at io.jenkins.plugins.opentelemetry.JenkinsOtelPluginFreestyleIntegrationTest.testFreestyleJob_with_ant_plugin(JenkinsOtelPluginFreestyleIntegrationTest.java:204)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:655)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

CI

### Reproduction steps

run the CI on master or the PR

### Expected Results

the test must pass

### Actual Results

the test fail

**Comment by cyrille-leclerc** [comment]
Fixed by 
* https://github.com/jenkinsci/opentelemetry-plugin/issues/775
