### ISSUE TITLE
NPE when restarting Jenkins with ongoing runs

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#934]
### Jenkins and plugins versions report

3.1368.vb_f1dcb_e6595c

### What Operating System are you using (both controller, and any agents involved in the problem)?

-

### Reproduction steps

```
2024-09-04 11:06:50.206+0000 [id=74]	WARNING	i.j.p.o.job.OtelTraceService#lambda$removePipelineStepSpanAndCloseAssociatedScopes$4: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} ending FlowNode[name: Shell Script, function: sh, id: 8] in sleep-3600-seconds #1
2024-09-04 11:06:50.254+0000 [id=77]	WARNING	i.j.p.o.job.OtelTraceService#lambda$removePipelineStepSpanAndCloseAssociatedScopes$4: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} ending FlowNode[name: Sleep 3600s, function: { (Sleep 3600s), id: 6] in sleep-3600-seconds #1
2024-09-04 11:06:50.339+0000 [id=77]	WARNING	i.j.p.o.job.OtelTraceService#lambda$removePipelineStepSpanAndCloseAssociatedScopes$4: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} ending FlowNode[name: Allocate node : Start, function: node, id: 3] in sleep-3600-seconds #1
2024-09-04 11:06:50.366+0000 [id=74]	WARNING	jenkins.util.Listeners#lambda$notify$0
java.lang.NullPointerException
	at io.jenkins.plugins.opentelemetry.job.action.AbstractMonitoringAction.getSpan(AbstractMonitoringAction.java:68)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.getPipelineRootSpan(OtelTraceService.java:83)
	at io.jenkins.plugins.opentelemetry.job.MonitoringRunListener.endPipelinePhaseSpan(MonitoringRunListener.java:332)
	at io.jenkins.plugins.opentelemetry.job.MonitoringRunListener._onCompleted(MonitoringRunListener.java:315)
	at io.jenkins.plugins.opentelemetry.job.opentelemetry.OtelContextAwareAbstractRunListener.onCompleted(OtelContextAwareAbstractRunListener.java:62)
	at hudson.model.listeners.RunListener.lambda$fireCompleted$0(RunListener.java:207)
	at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
	at jenkins.util.Listeners.notify(Listeners.java:67)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:205)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:645)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1068)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1582)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:512)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$2(CpsVmExecutorService.java:85)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-09-04 11:06:55.737+0000 [id=74]	WARNING	jenkins.util.Listeners#lambda$notify$0
java.lang.NullPointerException
	at io.jenkins.plugins.opentelemetry.job.action.AbstractMonitoringAction.getSpan(AbstractMonitoringAction.java:68)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.getPipelineRootSpan(OtelTraceService.java:83)
	at io.jenkins.plugins.opentelemetry.job.MonitoringRunListener.endPipelinePhaseSpan(MonitoringRunListener.java:332)
	at io.jenkins.plugins.opentelemetry.job.MonitoringRunListener._onFinalized(MonitoringRunListener.java:339)
	at io.jenkins.plugins.opentelemetry.job.opentelemetry.OtelContextAwareAbstractRunListener.onFinalized(OtelContextAwareAbstractRunListener.java:73)
	at hudson.model.listeners.RunListener.lambda$fireFinalized$3(RunListener.java:244)
	at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
	at jenkins.util.Listeners.notify(Listeners.java:67)
	at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:242)
	at hudson.model.Run.onEndBuilding(Run.java:2053)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:670)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1068)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1582)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:512)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$2(CpsVmExecutorService.java:85)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Expected Results

-

### Actual Results

-

**Comment by cyrille-leclerc** [comment]
Fix in 
* https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/3.1383.v32c9f94458e3

By PR
* https://github.com/jenkinsci/opentelemetry-plugin/pull/935
