### ISSUE TITLE
Need to monitor and troubleshoot problems to launch build agents 

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#95]
# Problem Description

The launch of build agents can have problems, administrators need to be alerted on, to monitor, and to troubleshoot these problems.

Example of problems
* Problem with the configuration of dynamic agents (invalid credentials...)
* Outage of underlying cloud provisioning infrastructure (no more VMs available, quota reached...)

# Solutions

Probably related to `hudson.slaves.ComputerListener#onLaunchFailure` but probably not enough.

**Comment by v1v** [comment]
I've been testing it out the `CloudProvisioningListener` interface with the Google Compute Engine plugin.

What have I seen so far?

- Google Compute Engine with `oneShot` configuration produces some stacktrace warnings

```
2021-05-21 12:02:51.759+0000 [id=100]	WARNING	hudson.slaves.NodeProvisioner#lambda$update$6: Unexpected exception encountered while provisioning agent obs11-ubuntu-18-linux-370cgd
java.io.IOException: Agent failed to connect, even though the launcher didn't report it. See the log output for details.
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:320)
	at hudson.slaves.SlaveComputer$$Lambda$264/0x0000000000000000.call(Unknown Source)
Caused: java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.lambda$getPlannedNodeFuture$0(ComputeEngineCloud.java:315)
	at com.google.jenkins.plugins.computeengine.ComputeEngineCloud$$Lambda$507/0x0000000000000000.call(Unknown Source)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
```

Even though the agent was created when the build requested an agent and removed afterwards.

Pipeline:

```
pipeline {
    agent {
      label 'linux'
    }

    stages {
        stage('Build') {
            steps {
                echo 'hi'
            }
        }
    }
}
```

<img width="1099" alt="Screenshot 2021-05-21 at 12 55 49" src="https://user-images.githubusercontent.com/2871786/119134826-8b6ad700-ba35-11eb-9ec0-f9945faa6af6.png">

<img width="1098" alt="Screenshot 2021-05-21 at 12 55 55" src="https://user-images.githubusercontent.com/2871786/119134919-a5a4b500-ba35-11eb-854b-e953e5d61178.png">

A bit of context, 
- [CloudProvisioningListener#onStarted](https://github.com/jenkinsci/jenkins/blob/36d70219e85d9c639a4b0ef8545d9bb5aa0567f4/core/src/main/java/hudson/slaves/NodeProvisioner.java#L723) is correctly executed.
- [CloudProvisioningListener#onFailure](https://github.com/jenkinsci/jenkins/blob/36d70219e85d9c639a4b0ef8545d9bb5aa0567f4/core/src/main/java/hudson/slaves/NodeProvisioner.java#L230-L243) is executed but I think it should not be since the worker was an ephemeral one and therefore the stacktrace should not happen after the build has finished correctly. 

As far as I see the Google Compute Engine uses the [OnceRetentionStrategy](https://github.com/jenkinsci/google-compute-engine-plugin/blob/bb7dcc6ffdd7b5f21a01817c76fbafc5a4765ea4/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineRetentionStrategy.java#L81-L89) when the task has finished and therefore the [taskCompleted](https://github.com/jenkinsci/durable-task-plugin/blob/574e7a6be7b2b5d1a38ff2e5012f255203c05466/src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java#L88-L90) is executed for the `AbstractCloudSlave`.

I'm not sure if we can use the `CloudProvisioningListener` without fixing the root cause error with the exceptions when using one shot workers.


What are your thoughts?

**Comment by v1v** [comment]
I've just asked in the [jenkins-dev-mailing-list](https://groups.google.com/g/jenkinsci-dev/c/ULfasawSRLU)

**Comment by v1v** [comment]
The issue with the `oneShot` provisioning seems to be fixed with the Jenkins core version in our test instance: `2.189.1`. 

![image](https://user-images.githubusercontent.com/2871786/123128120-c8febd80-d442-11eb-957b-6227926ec700.png)

**Comment by v1v** [comment]
Metrics are now available in the plugin, so I'd like now to move forward with the comment in https://github.com/jenkinsci/opentelemetry-plugin/pull/101#issuecomment-835869326 and tracking the provisioning of the cloud agents using a distributed trace.

Should both traces the one we are tracking so far, linked to the ci build, linked with the one for the cloud agents? I'm not sure whether it's possible though
