### ISSUE TITLE
Incompatibility with promoted-builds-plugin (or jobs of type freestyle?)

### ISSUE THREAD

**Issue by faandg** [jenkinsci/opentelemetry-plugin#994]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```Jenkins: 2.479.1
OS: Linux - 4.18.0-553.27.1.el8_10.x86_64
Java: 21.0.5 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:5.0.0
active-directory:2.38
analysis-model-api:12.9.1
ansicolor:1.0.5
ant:511.v0a_a_1a_334f41b_
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-124.v31e2987e48f4
asm-api:9.7.1-97.v4cc844130d97
authentication-tokens:1.119.v50285141b_7e1
authorize-project:1.8.1
azure-credentials:312.v0f3973cd1e59
azure-keyvault:251.vcfe31c013dc7
azure-sdk:184.v1f2c161c9777
azure-vm-agents:971.v88fcc9f5167c
badge:1.13
bitbucket:254.v9d8ec33a_7a_42
blueocean:1.27.16
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.16
blueocean-commons:1.27.16
blueocean-config:1.27.16
blueocean-core-js:1.27.16
blueocean-dashboard:1.27.16
blueocean-display-url:2.4.3
blueocean-events:1.27.16
blueocean-git-pipeline:1.27.16
blueocean-github-pipeline:1.27.16
blueocean-i18n:1.27.16
blueocean-jira:1.27.16
blueocean-jwt:1.27.16
blueocean-personalization:1.27.16
blueocean-pipeline-api-impl:1.27.16
blueocean-pipeline-editor:1.27.16
blueocean-pipeline-scm-api:1.27.16
blueocean-rest:1.27.16
blueocean-rest-impl:1.27.16
blueocean-web:1.27.16
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1200.v4b_a_3da_2eb_db_4
build-discarder:139.v05696a_7fe240
build-name-setter:2.4.3
build-timestamp:1.0.4
build-user-vars-plugin:182.v378b_9f14b_487
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
cloud-stats:336.v788e4055508b_
cloudbees-bitbucket-branch-source:914.vc8c12e22f10e
cloudbees-folder:6.959.v4ed5cc9e2dd4
command-launcher:116.vd85919c54a_d6
commons-compress-api:1.26.1-2
commons-httpclient3-api:3.1-3
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
config-file-provider:980.v88956a_a_5d6a_d
copyartifact:757.v05365583a_455
coverage:1.16.1
credentials:1389.vd7a_b_f5fa_50a_2
credentials-binding:687.v619cb_15e923f
cucumber-perf:2.0.9
cucumber-reports:5.8.5
dark-theme:479.v661b_1b_911c01
data-tables-api:2.1.8-1
display-url-api:2.209.v582ed814ff2f
docker-commons:445.v6b_646c962a_94
docker-java-api:3.4.0-94.v65ced49b_a_7d5
docker-workflow:580.vc0c340686b_54
durable-task:577.v2a_8a_4b_7c0247
echarts-api:5.5.1-4
eddsa-api:0.3.0-4.v84c6f0f4969e
elastic-axis:615.vb_f7c20ec040e
email-ext:1855.vd9e491cb_de1e
embeddable-build-status:487.va_0ef04c898a_2
extended-read-permission:53.v6499940139e5
external-monitor-job:215.v2e88e894db_f8
favorite:2.221.v19ca_666b_62f5
file-parameters:339.v4b_cc83e11455
font-awesome-api:6.6.0-2
forensics-api:2.6.0
generic-webhook-trigger:2.2.5
git:5.6.0
git-client:6.1.0
git-parameter:0.10.0
git-server:126.v0d945d8d2b_39
github:1.40.0
github-api:1.321-478.vc9ce627ce001
github-branch-source:1807.v50351eb_7dd13
google-oauth-plugin:1.330.vf5e86021cb_ec
gson-api:2.11.0-85.v1f4e87273c33
h2-api:11.1.4.199-30.v1c64e772f3a_c
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.37
http_request:1.19
image-tag-parameter:2.0
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:280.v050b_5c849f69
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jenkins-design-language:1.27.16
jersey2-api:2.44-151.v6df377fff741
jira:3.13
jira-steps:2.0.165.v8846cf59f3db
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jnr-posix-api:3.1.19-2
joda-time-api:2.13.0-93.v9934da_29b_a_e9
jquery:1.12.4-3
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-101.v7a_8666713110
json-path-api:2.9.0-118.v7f23ed82a_8b_8
junit:1309.v0078b_fecd6ed
junit-attachments:239.v9e003a_c80a_8c
kubernetes:4296.v20a_7e4d77cf6
kubernetes-cli:1.12.1
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:189.v90a_488b_d1d65
last-changes:2.7.12
ldap:770.vb_455e934581a_
leastload:62.vfa_8830902733
lighthouse-report:1.3.0
lockable-resources:1327.ved786b_a_197e0
mailer:489.vd4b_25144138f
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.2.3
matrix-project:840.v812f627cb_578
maven-plugin:3.24
maven-snapshot-check:1106.v529e6b_c11e8e
mercurial:1260.vdfb_723cdcc81
metrics:4.2.21-458.vcf496cb_839e4
mina-sshd-api-common:2.14.0-133.vcc091215a_358
mina-sshd-api-core:2.14.0-133.vcc091215a_358
multibranch-scan-webhook-trigger:1.0.11
nexus-jenkins-plugin:3.16.491.v77a_2f8921c88
nodejs:1.6.2
nodelabelparameter:1.13.0
oauth-credentials:0.653.v14cf2088e950
okhttp-api:4.11.0-181.v1de5b_83857df
openshift-client:1.1.0.424.v829cb_ccf8798
opentelemetry:3.1423.v0d1a_2fcd2429
opentelemetry-api:1.43.0-38.v1a_9b_53e3f70f
pam-auth:1.11
parameterized-trigger:806.vf6fff3e28c3e
performance:970.ve5406a_d8c219
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:744.v5b_556ee7c253
pipeline-input-step:495.ve9c153f6067b_
pipeline-maven:1457.vf7a_de13b_c0d4
pipeline-maven-api:1457.vf7a_de13b_c0d4
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2218.v56d0cda_37c72
pipeline-model-definition:2.2218.v56d0cda_37c72
pipeline-model-extensions:2.2218.v56d0cda_37c72
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2218.v56d0cda_37c72
pipeline-stage-view:2.34
pipeline-utility-steps:2.18.0
plain-credentials:183.va_de8f1dd5a_2b_
platformlabeler:2734.v604521b_646b_b_
plugin-usage-plugin:4.8
plugin-util-api:5.1.0
postbuild-task:1.9
prism-api:1.29.0-18
prometheus:795.v995762102f28
promoted-builds:965.vcda_c6a_e0998f
pubsub-light:1.18
role-strategy:743.v142ea_b_d5f1d3
run-condition:1.7
saml:4.501.v4313a_01e3a_18
scm-api:698.v8e3b_c788f0a_6
script-security:1369.v9b_98a_4e95b_2d
slack:751.v2e44153c8fe1
snakeyaml-api:2.3-123.v13484c65210a_
soapui-pro-functional-testing:1.11
sonar:2.17.3
sonar-quality-gates:328.vf4369b_da_d3c2
sse-gateway:1.27
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
strict-crumb-issuer:2.1.1
structs:338.v848422169819
subversion:1281.vc8837f91a_07a_
theme-manager:262.vc57ee4a_eda_5d
timestamper:1.28
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
validating-string-parameter:251.vc34e592b_8a_4d
variant:60.v7290fc0eb_b_cd
versioncolumn:243.vda_c20eea_a_8a_f
warnings-ng:11.12.0
windows-azure-storage:454.v573775e9feef
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3996.va_f5c1799f978
workflow-durable-task-step:1398.vf6c9e89e5988
workflow-job:1468.vcf4f5ee92395
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:936.v9fa_77211ca_e1
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Red Hat Enterprise Linux 8.10

### Reproduction steps

1. install promoted builds plugin, configure a simple promotion and have any pipeline or multibranch pipeline declaratively start a promotion (job type of these is freestyle, perhaps this is why there is an incompatibility)
2. install OpenTelemetry plugin (no need to configure it)
3. run the build -> build is marked als FAILED due to a fatal error related to the open telemetry plugin

### Expected Results

Expected result would be to either properly execute (compatible with the promoted builds plugin) or to handle the exception so the build itself does not fail (perhaps rather throw a warning that inspection failed or something incompatible is found and skip further inspection)

### Actual Results

stacktrace executing builds from the promoted-builds-plugin:

```
Started by upstream project "[team-hybrid-cloud/deployable_app/apache-redirect/master](https://<redacted>/job/team-hybrid-cloud/job/deployable_app/job/apache-redirect/job/master/)" build number [39](https://<redacted>/job/team-hybrid-cloud/job/deployable_app/job/apache-redirect/job/master/39)
originally caused by:
 Started by user <redacted>
Running as SYSTEM
Building remotely on [Builder002_RHEL](https://<redacted>/computer/Builder002_RHEL) (linux builder RHEL8 builder002) in workspace /var/lib/jenkins/workspace/team-hybrid-cloud/promotion-pipeline-merged-w-version-adjust
No emails were triggered.
New run name is 'apache-redirect-1.3.2'
[promotion-pipeline-merged-w-version-adjust] $ /bin/sh -xe /tmp/jenkins14378402096269050164.sh
+ echo 'Ready for promotion'
Ready for promotion
New run name is 'apache-redirect-1.3.2'
FATAL: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.tasks.Shell@6fcdb4d2
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.tasks.Shell@6fcdb4d2
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:527)
	at hudson.model.Run.execute(Run.java:1831)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
```

### Anything else?

Disabling the opentelemetry-plugin, promoted-builds-plugin builds work again so it seems like a plugin incompatibility issue.

### Are you interested in contributing a fix?

No, unfortunately no experience developing jenkins plugins

**Comment by faandg** [comment]
Sorry, couple more lines to the stack trace although it's mostly the same stuff.

```
FATAL: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.tasks.Shell@6fcdb4d2
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.tasks.Shell@6fcdb4d2
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:527)
	at hudson.model.Run.execute(Run.java:1831)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
ERROR: Step ‘Associated Jira’ aborted due to exception: 
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.plugins.jira.JiraProjectProperty@78185ec5
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:742)
	at hudson.model.Build$BuildExecution.post2(Build.java:181)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1854)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
ERROR: Step ‘Discard old builds’ aborted due to exception: 
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for jenkins.model.BuildDiscarderProperty@58a11d6a
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:742)
	at hudson.model.Build$BuildExecution.post2(Build.java:181)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1854)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
ERROR: Step ‘Least Load Disabled Property’ aborted due to exception: 
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for org.bstick12.jenkinsci.plugins.leastload.LeastLoadDisabledProperty@3d457d3
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:742)
	at hudson.model.Build$BuildExecution.post2(Build.java:181)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1854)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
ERROR: Step ‘Promote Builds When...’ aborted due to exception: 
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.plugins.promoted_builds.JobPropertyImpl@616adaf2
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:742)
	at hudson.model.Build$BuildExecution.post2(Build.java:181)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1854)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
ERROR: Step ‘This project is parameterized’ aborted due to exception: 
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.model.ParametersDefinitionProperty@e6c030c
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:742)
	at hudson.model.Build$BuildExecution.post2(Build.java:181)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1854)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
No emails were triggered.
ERROR: Step ‘Editable Email Notification’ aborted due to exception: 
java.lang.IllegalStateException: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} for hudson.plugins.emailext.ExtendedEmailPublisher@602fe1a6
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$removeBuildStepSpan$6(OtelTraceService.java:209)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.OtelTraceService.removeBuildStepSpan(OtelTraceService.java:208)
	at PluginClassLoader for opentelemetry//io.jenkins.plugins.opentelemetry.job.MonitoringBuildStepListener.finished(MonitoringBuildStepListener.java:92)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:827)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:189)
	at hudson.model.Run.execute(Run.java:1874)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:445)
Finished: FAILURE
```

**Comment by sparrowt** [comment]
I'm seeing a slightly related issue with `span not found to be purged` though in my case it's just a WARNING log line e.g:
```
WARNING i.j.p.o.job.OtelTraceService#lambda$removePipelineStepSpanAndCloseAssociatedScopes$4: span not found to be purged: PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}} ending FlowNode[name: Branch: branch 2, function: { (Branch: branch 2), id: 9] in MyJobName #746
```
and doesn't cause the job to fail.

I don't have `promoted-builds-plugin` installed so this is not the exact same issue, but posting here as the message is very similar, in case it is relevant at all - in my case it is a very simple `pipelineJob`, so perhaps there's an underlying problem that is not specific to the promoted-builds-plugin or freestyle jobs seeing as I have neither?

**Comment by kuisathaverat** [comment]
probably related to https://github.com/jenkinsci/opentelemetry-plugin/issues/1088
